# Generated by Django 5.2.5 on 2025-08-26 02:25

import datetime
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите название места",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "map",
                    location_field.models.plain.PlainLocationField(
                        blank=True,
                        max_length=63,
                        null=True,
                        verbose_name="Карта и координаты",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Укажите время", max_length=30, verbose_name="Время"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=30,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "sign_of_a_pleasant_habit",
                    models.BooleanField(
                        help_text="Укажите, является ли данная привычка приятной",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "related_habit",
                    models.CharField(
                        blank=True,
                        help_text="Название связанной приятной привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        help_text="Укажите период времени в формате ЧЧ:ММ:СС",
                        verbose_name="Период",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="Напишите какое вознаграждение после выполнения",
                        max_length=300,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        help_text="Укажите время на выполнение привычки в формате ЧЧ:ММ:СС",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "sign_of_publicity",
                    models.BooleanField(
                        help_text="Укажите, нужно ли опубликовать привычку",
                        verbose_name="Опубликовать",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action", "related_habit", "user", "place", "time"],
            },
        ),
    ]
