# Generated by Django 5.2.5 on 2025-08-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                default=2,
                help_text="Владелец объекта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits_as_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                help_text="Выберите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits_as_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
