# Generated by Django 5.2.5 on 2025-08-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_owner_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Укажите время", max_length=30, verbose_name="Время"
            ),
        ),
    ]
