# Generated by Django 5.2.5 on 2025-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["action", "related_habit", "place", "time"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
