# Generated by Django 5.2.5 on 2025-09-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_alter_habit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["action", "place", "time"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
